### ISSUE TITLE
Water in het chunk systeem heeft zichtbare lijnen.

### ISSUE THREAD

**Issue by JudaHensen** [JudaHensen/PVB_Team10#3]
Het water in het chunk systeem is gemaakt uit meerdere aangrenzende planes.
Wanneer je te dicht bij een aanliggende plane komt zie je duidelijk lijnen waar de planes elkaar aan liggen.

**Comment by MikeRaadsheer** [comment]
Omdat de shader licht is om te gebruiken hebben we besloten de plane van de shader gewoon grooter te maken en het chunk systeem te schrappen voor nu gezien de komende deadlines en prioriteiten.
