### ISSUE TITLE
Wanneer de chunks verplaatst worden is dit visueel zichtbaar.

### ISSUE THREAD

**Issue by JudaHensen** [JudaHensen/PVB_Team10#4]
Het moment dat de chunks verplaatst worden is dit zichbaar omdat de chunks andere timing hebben, of omdat de shader niet een perfecte loop is.

**Comment by MikeRaadsheer** [comment]
Gezien de shader voor het water niet erg intense is om te runnen en de game als demo bedoeld is hebben we besloten de plane van het water te vergroten en het chunk systeem te laten vallen.
